# Generated by Django 4.1 on 2022-09-07 06:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='total_likes',
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 7, 12, 11, 26, 686714)),
        ),
        migrations.AlterField(
            model_name='product',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 10, 12, 11, 26, 685713)),
        ),
        migrations.AlterField(
            model_name='product',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 7, 12, 11, 26, 685713)),
        ),
    ]
