# Generated by Django 4.1 on 2022-09-07 07:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_bid_bid_time_alter_product_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='buyer_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.buyer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 7, 12, 42, 26, 64516)),
        ),
        migrations.AlterField(
            model_name='product',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 10, 12, 42, 26, 64516)),
        ),
        migrations.AlterField(
            model_name='product',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 7, 12, 42, 26, 64516)),
        ),
    ]
