# Generated by Django 4.1 on 2022-09-07 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_bid_buyer_id_alter_bid_bid_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='bid_amount',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 7, 15, 16, 29, 442078)),
        ),
        migrations.AlterField(
            model_name='product',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 10, 15, 16, 29, 442078)),
        ),
        migrations.AlterField(
            model_name='product',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 7, 15, 16, 29, 442078)),
        ),
    ]
